const fs = require('fs');

let dataFile = fs.readFileSync('src/data.ts', 'utf8');

// The new items to add
const newItems = [
  { name: 'Devasahayam Pillai', role: 'Early Indian Christian Martyr & Lay Witness', year: '1712–1752 AD', badgeType: 'native', badgeLabel: 'Martyr', icon: 'cross', description: 'Born Neelakanda Pillai, Devasahayam served in the Travancore royal administration before converting to Catholic Christianity in 1745 and taking the name Lazarus/Devasahayam. He faced persecution, imprisonment and execution for his faith, and was shot at Aralvaimozhy on 14 January 1752. He was canonized by Pope Francis in 2022 and is recognized as the first Indian layperson and martyr canonized by the Catholic Church.', image: 'images/devasahayam.jpg' },
  { name: 'Nehemiah Goreh', role: 'Indian Theologian, Sanskrit Scholar & Christian Apologist', year: '1825–1895 AD', badgeType: 'native', badgeLabel: 'Theologian', icon: 'book', description: 'Born Nilakantha Sastri Goreh, Nehemiah Goreh was a Sanskrit scholar from a Brahmin family who converted to Christianity in 1848. He became an ordained Christian minister and wrote extensively on Hindu philosophical systems and Christian theology, seeking to engage Indian intellectual traditions directly. His works included A Rational Refutation of the Hindu Philosophical Systems.', image: 'images/nehemiah-goreh.jpg' },
  { name: 'Narayan Vaman Tilak', role: 'Marathi Christian Poet, Hymnist & Indigenous Christian Thinker', year: '1861–1919 AD', badgeType: 'poet', badgeLabel: 'Poet & Hymnist', icon: 'music', description: 'Narayan Vaman Tilak was a Marathi poet who converted to Christianity and was baptized in 1895. Influenced by the Marathi devotional tradition of Tukaram, he sought to express Christian faith through Indian cultural and poetic forms. He produced numerous Marathi Christian poems and hymns and became an important voice in the development of indigenous Indian Christian hymnody.', image: 'images/tilak.jpg' },
  { name: 'Brahmabandhav Upadhyay', role: 'Indian Christian Theologian, Vedantic Thinker & Nationalist', year: '1861–1907 AD', badgeType: 'native', badgeLabel: 'Theologian', icon: 'church', description: 'Born Bhavani Charan Bandyopadhyay, Brahmabandhav Upadhyay became an influential Bengali Christian thinker who attempted to express Christian theology through Indian philosophical categories. He developed the idea of an indigenous Indian Christian identity and engaged deeply with Vedanta, Catholic theology and Indian nationalism. He also worked as a journalist and public intellectual.', image: 'images/upadhyay.jpg' },
  { name: 'Lal Behari Day', role: 'Bengali Christian Writer, Educator & Missionary', year: '1824–1894 AD', badgeType: 'native', badgeLabel: 'Writer & Educator', icon: 'book', description: 'Lal Behari Day was an Indian Bengali writer, journalist, educator and Christian missionary. Educated at Alexander Duff\'s institution in Calcutta, he became an important voice in Bengali literature and vernacular education. His writings helped preserve Bengali folk traditions, while his Christian ministry and educational work contributed to the development of indigenous Christian intellectual life in Bengal.', image: 'images/lal-behari-day.jpg' }
];

// parse the existing items
// Because we have TypeScript, we'll do a simple trick: use regex to pull out the objects, or just do it manually.
