import { Era, Item } from './types';

export const eras: Era[] = [
  { id: 'era-1', number: 1, title: 'Apostolic Foundations & Early Classical Inculturation', subtitle: 'Entries #01 to #07 • Apostolic roots, Konkani epics, and classical Tamil inculturation.' },
  { id: 'era-2', number: 2, title: 'Tranquebar, First Native Hymnologists & Serampore', subtitle: 'Entries #08 to #21 • Vernacular printing, Carnatic Christian lyrics, and Serampore linguistics.' },
  { id: 'era-3', number: 3, title: 'Southern & Regional Institutional Pioneers', subtitle: 'Entries #22 to #31 • Social reformers, Malayalam typography, and Tirunelveli mission builders.' },
  { id: 'era-4', number: 4, title: 'Classical Poets, Keerthanai Masters & Scholars', subtitle: 'Entries #32 to #46 • The golden age of Tamil Christian Keerthanai, epics, linguistics, and literature.' },
  { id: 'era-5', number: 5, title: 'Musicologists, Revivalists, Medical Pioneers & Indigenous Bishops', subtitle: 'Entries #47 to #55 • Carnatic musicology, Marathi Christian poetry, Dohnavur, and indigenous bishops.' }
];

export const allItems: Item[] = [
  // ERA 1
  { id: '01', name: 'St. Thomas the Apostle', role: 'Apostle of India & Founder of the St. Thomas (Nasrani) Christian Community', eraId: 'era-1', year: 'c. 52 – 72 AD', badgeType: 'foreign', badgeLabel: 'Apostolic Pioneer', icon: 'cross', description: 'Landed at Muziris (Kodungallur, Kerala) in 52 AD. Established seven and a half churches along the Malabar Coast and traveled to the Coromandel Coast before his martyrdom at Mylapore (Chennai).', image: 'images/st-thomas.jpg' },
  { id: '02', name: 'Francis Xavier', role: 'Co-Founder of the Society of Jesus & Apostle to the Indies', eraId: 'era-1', year: '1542 – 1552 AD', badgeType: 'foreign', badgeLabel: 'Jesuit Pioneer', icon: 'church', description: 'Evangelized the Paravar pearl-fisher community along the Fishery Coast, translated basic prayers into Tamil, and established St. Paul\'s College in Goa.', image: 'images/francis-xavier.jpg' },
  { id: '03', name: 'Antony Criminali (Antonio Criminali)', role: 'First Superior of the Fishery Coast Mission & First Jesuit Martyr in India', eraId: 'era-1', year: '1545 – 1549 AD', badgeType: 'foreign', badgeLabel: 'Jesuit Martyr', icon: 'church', description: 'Appointed by Francis Xavier to supervise the Fishery Coast mission. He learned Tamil, organized systematic village schooling, and was martyred at Vedalai.', image: 'images/antony-criminali.jpg' },
  { id: '04', name: 'Thomas Stephens', role: 'Author of the Krista Purana & First Grammar of Konkani (Goa)', eraId: 'era-1', year: '1579 – 1619 AD', badgeType: 'poet', badgeLabel: 'Jesuit Epic Poet', icon: 'music', description: 'Mastered Konkani and Marathi in Goa. Composed the *Krista Purana* (1616)—a massive Christian epic in classical Marathi/Konkani verse—and published the first printed grammar of an Indian language.', image: 'images/thomas-stephens.jpg' },
  { id: '05', name: 'Roberto de Nobili (Tattuva Podagar)', role: 'Pioneer of Christian Inculturation (Accommodatio) & Sanskrit-Tamil Scholar', eraId: 'era-1', year: '1606 – 1656 AD', badgeType: 'foreign', badgeLabel: 'Madurai Mission', icon: 'book', description: 'Adopted the saffron dress, vegetarian diet, and customs of an Indian ascetic (Sannyasi) in Madurai. Mastered Sanskrit and Tamil, authoring pioneering Christian theological treatises in Tamil.', image: 'images/roberto-de-nobili.jpg' },
  { id: '06', name: 'John de Britto (Arul Anandar)', role: 'Jesuit Missionary in Madurai & Martyr of Oriyur (Ramnad)', eraId: 'era-1', year: '1673 – 1693 AD', badgeType: 'foreign', badgeLabel: 'Evangelist Martyr', icon: 'church', description: 'Lived as a wandering ascetic (Pandaraswami) in the Maravar Kingdom. Evangelized rural Tamil Nadu and was martyred at Oriyur in 1693.', image: 'images/john-de-britto.jpg' },
  { id: '07', name: 'Veeramamunivar (Costanzo Giuseppe Beschi)', role: 'Author of Thembavani, Lexicographer, and Orthographic Reformer', eraId: 'era-1', year: '1710 – 1747 AD', badgeType: 'poet', badgeLabel: 'Tamil Epic Poet', icon: 'music', description: 'Authored the classical Tamil Christian epic *Thembavani* (தேம்பாவணி), compiled *Chaturakarathi*, and introduced fundamental orthographic reforms to the Tamil script.', image: 'images/veeramamunivar.jpg' },

  // ERA 2
  { id: '08', name: 'Bartholomäus Ziegenbalg', role: 'First Protestant Missionary to India & Pioneer of the Tamil Printing Press', eraId: 'era-2', year: '1706 – 1719 AD', badgeType: 'foreign', badgeLabel: 'Danish-Halle Press', icon: 'book', description: 'Established India\'s first vernacular Protestant press at Tranquebar in 1712, completed the first Tamil New Testament, and opened egalitarian schools.', image: 'images/ziegenbalg.jpg' },
  { id: '09', name: 'Heinrich Plütschau', role: 'Co-Founder of the Tranquebar Mission & Pioneer of Portuguese-Medium Ministry', eraId: 'era-2', year: '1706 – 1711 AD', badgeType: 'foreign', badgeLabel: 'Tranquebar Pioneer', icon: 'church', description: 'Arrived with Ziegenbalg in 1706. Oversaw early educational schools and Portuguese-medium congregations before returning to Europe to mobilize mission support.', image: 'images/plutschau.jpg' },
  { id: '10', name: 'Benjamin Schultze', role: 'Completer of the First Tamil Bible & Telugu/Hindustani Translator', eraId: 'era-2', year: '1719 – 1743 AD', badgeType: 'foreign', badgeLabel: 'Bible Translator', icon: 'book', description: 'Completed the translation of the Old Testament into Tamil (1728), founded the English-supported SPCK mission at Madras (Vepery), and translated portions of scripture into Telugu and Dakhini.', image: 'images/benjamin-schultze.jpg' },
  { id: '11', name: 'Johann Philip Fabricius', role: 'Master of Tamil Translation, Hymnologist & Lexicographer (Madras)', eraId: 'era-2', year: '1740 – 1791 AD', badgeType: 'poet', badgeLabel: 'Tamil Hymnologist', icon: 'music', description: 'Produced the acclaimed *Fabricius Version* of the Tamil Bible and compiled the foundational *English and Malabar Dictionary* (1779), translating classic German hymns into Tamil meters.', image: 'images/fabricius.jpg' },
  { id: '12', name: 'Christian Frederick Schwarz', role: 'Apostle to South India, Peace Envoy & Mentor to Raja Serfoji II', eraId: 'era-2', year: '1750 – 1798 AD', badgeType: 'foreign', badgeLabel: 'Royal Envoy & Pastor', icon: 'church', description: 'Stationed in Tiruchirappalli and Thanjavur. Trusted as a peace mediator by Hyder Ali, he served as guardian-tutor to Serfoji II and nurtured early native hymnists.', image: 'images/cf-schwarz.jpg' },
  { id: '13', name: 'Arumai Nayagam Sathianathan', role: 'First Ordained Indian Protestant Minister & Pioneer Rural Hymnist', eraId: 'era-2', year: '1752 – 1815 AD', badgeType: 'poet', badgeLabel: 'Native Pastor & Hymnist', icon: 'music', description: 'Ordained by C. F. Schwarz in 1790 at Thanjavur. He supervised congregations across Tirunelveli and Ramanathapuram, composing early indigenous Tamil Christian lyrics that rooted congregational singing in rural villages.', image: 'images/sathianathan-thanjavur.jpg' },
  { id: '14', name: 'Clarinda (Raza Clarinda / Kokila)', role: 'First Protestant Convert of Tirunelveli & Builder of Clarinda Church', eraId: 'era-2', year: 'c. 1746 – 1806 AD', badgeType: 'native', badgeLabel: 'Church Founder', icon: 'church', description: 'A Maratha royal widow baptized by C. F. Schwarz in 1778. She personally financed and constructed the historic Clarinda Church (1785) in Palayamkottai.', image: 'images/clarinda.jpg' },
  { id: '15', name: 'Thadikombu Thaveedu (David) Sundaranandan', role: 'Pioneer Indigenous Catechist of Mudalur & South Tirunelveli', eraId: 'era-2', year: 'c. 1770 – 1806 AD', badgeType: 'native', badgeLabel: 'Native Evangelist', icon: 'church', description: 'Led early converts from persecution to establish Mudalur ("First Village") in 1799, organizing self-supporting agricultural settlements across southern Tirunelveli.', image: 'images/thaveedu-sundaranandan.jpg' },
  { id: '16', name: 'Vethanayagam Sastriyar', role: 'Gnanakkavi Chakkravarthi & Court Poet to Serfoji II of Thanjavur', eraId: 'era-2', year: '1774 – 1864 AD', badgeType: 'poet', badgeLabel: 'Father of Keerthanai', icon: 'music', description: 'The foremost pioneer of indigenous Christian music. Set Christian theology to classical Carnatic ragas and Kathakalakshepam storytelling. Authored *Bethlehem Kuravanji*, *Jebamalai*, and over 400 classical keerthanaigal.', highlights: ['Composed timeless classics: "Aararo Aariraro En Kannin Maniye", "Thasare Iththaraniyai Anbaai".', 'Established the royal Sastriyar lineage of Christian musical performance.'], image: 'images/vethanayagam-sastriyar.jpg' },
  { id: '17', name: 'John Thomas (Bengal Surgeon)', role: 'Pioneer Medical Missionary in Bengal & Carey\'s Co-Traveler (1793)', eraId: 'era-2', year: '1786 – 1801 AD', badgeType: 'foreign', badgeLabel: 'Medical Missionary', icon: 'medical', description: 'Accompanied William Carey to Bengal in 1793, treated thousands at Malda and Serampore, and baptized Krishna Pal (the first Bengali convert and early Bengali hymn writer).', image: 'images/john-thomas-bengal.jpg' },
  { id: '18', name: 'William Carey', role: 'Father of Modern Missions, Orientalist, Botanist & Social Reformer', eraId: 'era-2', year: '1793 – 1834 AD', badgeType: 'foreign', badgeLabel: 'Serampore Mission', icon: 'book', description: 'Co-founded the Serampore Mission, translated scriptures into over 30 Indian languages/dialects, founded Serampore College (1818), and campaigned to legally abolish Sati (1829).', image: 'images/william-carey.jpg' },
  { id: '19', name: 'Joshua Marshman', role: 'Co-Founder of Serampore College, Chinese Scholar & Educator', eraId: 'era-2', year: '1799 – 1837 AD', badgeType: 'foreign', badgeLabel: 'Serampore Trio', icon: 'book', description: 'Member of the Serampore Trio. Managed extensive schooling networks, drafted the royal charter for Serampore College, and translated the Bible into Chinese.', image: 'images/joshua-marshman.jpg' },
  { id: '20', name: 'William Ward', role: 'Master Printer, Multilingual Publisher & Historian of Indian Culture', eraId: 'era-2', year: '1799 – 1823 AD', badgeType: 'foreign', badgeLabel: 'Master Printer', icon: 'book', description: 'The operational engine of the Serampore Press, casting indigenous metal typefaces for over 40 languages and publishing vernacular literature.', image: 'images/william-ward.jpg' },
  { id: '21', name: 'Henry Martyn', role: 'Pioneer Translator of the New Testament into Hindustani, Urdu, and Persian', eraId: 'era-2', year: '1806 – 1812 AD', badgeType: 'foreign', badgeLabel: 'Chaplain & Translator', icon: 'church', description: 'In just six years of intensive labor before his early death, he translated the New Testament into Urdu, Persian, and Arabic.', image: 'images/henry-martyn.jpg' },

  // ERA 3
  { id: '22', name: 'William Tobias Ringeltaube', role: 'Founder of the London Missionary Society (LMS) in South Travancore (Mylaudy)', eraId: 'era-3', year: '1806 – 1816 AD', badgeType: 'foreign', badgeLabel: 'LMS Pioneer', icon: 'church', description: 'Lived in austere simplicity among the marginalized communities of South Travancore, founding schools and fighting caste indignities.', image: 'images/ringeltaube.jpg' },
  { id: '23', name: 'Charles Mead', role: 'Father of the South Travancore Mission & Social Emancipator', eraId: 'era-3', year: '1817 – 1873 AD', badgeType: 'foreign', badgeLabel: 'LMS Reformer', icon: 'church', description: 'Stationed in Nagercoil. Introduced printing and industrial training, championing the *Upper Cloth Revolt* for the dignity of lower-caste women.', image: 'images/charles-mead.jpg' },
  { id: '24', name: 'Benjamin Bailey', role: 'Father of Modern Malayalam Printing, Lexicographer & Bible Translator', eraId: 'era-3', year: '1817 – 1850 AD', badgeType: 'foreign', badgeLabel: 'Malayalam Scholar', icon: 'book', description: 'Cast the first modern round Malayalam typography, founded CMS Press Kottayam (1821), and translated the complete Malayalam Bible (1841).', image: 'images/benjamin-bailey.jpg' },
  { id: '25', name: 'Charles & Martha Mault', role: 'Pioneers of Girls\' Education & the Nagercoil Pillow-Lace Industry', eraId: 'era-3', year: '1819 – 1858 AD', badgeType: 'foreign', badgeLabel: 'LMS Educators', icon: 'church', description: 'Served at Nagercoil for four decades. Martha introduced the famous pillow-lace industry providing economic self-reliance for native women.', image: 'images/charles-martha-mault.jpg' },
  { id: '26', name: 'John Scudder Sr.', role: 'First Western Medical Missionary in India & Founder of Scudder Medical Dynasty', eraId: 'era-3', year: '1819 – 1855 AD', badgeType: 'foreign', badgeLabel: 'Medical Pioneer', icon: 'medical', description: 'American physician and minister who established dispensaries combining modern surgical/medical treatment with evangelism across South India.', image: 'images/john-scudder-sr.jpg' },
  { id: '27', name: 'C.T.E. Rhenius (Charles Theophilus Ewald Rhenius)', role: 'The "Apostle of Tirunelveli" & Modern Tamil Grammarian', eraId: 'era-3', year: '1820 – 1838 AD', badgeType: 'foreign', badgeLabel: 'CMS Pioneer', icon: 'church', description: 'Transformed Tirunelveli through Christian agricultural colonies (Nazareth, Asirvathapuram), authored *A Grammar of the Tamil Language*, and trained native catechists.', image: 'images/cte-rhenius.jpg' },
  { id: '28', name: 'Rev. J.T.G. Barenbruck', role: 'CMS Pioneer in Mayiladuthurai (Mayavaram) & Madras', eraId: 'era-3', year: '1817 – 1835 AD', badgeType: 'foreign', badgeLabel: 'CMS Educationist', icon: 'church', description: 'Pioneered primary education in Madras and Mayiladuthurai (Mayavaram), establishing teacher-training seminaries and schools open to all castes.', image: 'images/barenbruck.jpg' },
  { id: '29', name: 'John Wilson', role: 'Founder of Wilson College (Bombay), Orientalist & Vice-Chancellor of Bombay University', eraId: 'era-3', year: '1829 – 1875 AD', badgeType: 'foreign', badgeLabel: 'Scottish Orientalist', icon: 'book', description: 'Scottish missionary-scholar in Western India. Mastered Marathi, Gujarati, and Sanskrit, founded Wilson College (1832), and championed female education.', image: 'images/john-wilson.jpg' },
  { id: '30', name: 'John Thomas (of Mengnanapuram)', role: 'Architect & Builder of Mengnanapuram (Village of True Wisdom)', eraId: 'era-3', year: '1838 – 1870 AD', badgeType: 'foreign', badgeLabel: 'CMS Builder', icon: 'church', description: 'Transformed the arid desert wastes of southern Tirunelveli into an oasis and built the monumental Gothic St. John\'s Church with its 192-foot spire.', image: 'images/john-thomas-mengnanapuram.jpg' },
  { id: '31', name: 'Rev. John Thomas Tucker', role: 'Pioneer of the Pannivilai (Panneivillai) Mission District', eraId: 'era-3', year: '1842 – 1866 AD', badgeType: 'foreign', badgeLabel: 'CMS Evangelist', icon: 'church', description: 'CMS missionary who founded Pannivilai station, building over 40 village churches and establishing boarding schools for girls in rural Tirunelveli.', image: 'images/john-thomas-tucker.jpg' },

  // ERA 4
  { id: '32', name: 'Mayuram Vedanayakam Pillai', role: 'District Munsif, First Modern Tamil Novelist & Composer of Samarasa Keerthanai', eraId: 'era-4', year: '1826 – 1889 AD', badgeType: 'poet', badgeLabel: 'Keerthanai Composer', icon: 'music', description: 'Distinguished scholar and judge who authored *Prathapa Mudaliar Charithram* (the first modern Tamil novel) and composed the celebrated *Sarva Samaya Samarasa Keerthanai*—classical Carnatic songs on ethics, justice, and devotion to God.', image: 'images/mayuram-vedanayakam-pillai.jpg' },
  { id: '33', name: 'Henry Alfred Krishnapillai (H. A. Krishna Pillai)', role: 'The "Christian Kambar" & Author of Rakshanya Yathrigam', eraId: 'era-4', year: '1827 – 1900 AD', badgeType: 'poet', badgeLabel: 'Christian Kambar', icon: 'music', description: 'Foremost Tamil Christian classical poet. Authored *Rakshanya Yathrigam* (3,766 verses adapted from Bunyan\'s *Pilgrim\'s Progress* in Sangam meter), *Rakshanya Manoharam*, *Rakshanya Kural*, and renowned keerthanaigal.', highlights: ['Composed classical keerthanai: "Aanandha Meikkanbaa - En Kaanbaai", "Karthar Ratchippu Namakku".'], image: 'images/ha-krishnapillai.jpg' },
  { id: '34', name: 'Alexander Duff', role: 'Pioneer of English Higher Education in Bengal & Founder of Scottish Church College', eraId: 'era-4', year: '1830 – 1863 AD', badgeType: 'foreign', badgeLabel: 'Scottish Educationist', icon: 'book', description: 'Combined modern Western sciences and English higher education with biblical studies in Calcutta, heavily shaping the 19th-century Bengal Renaissance.', image: 'images/alexander-duff.jpg' },
  { id: '35', name: 'Rev. Krishna Mohan Banerjee (K. M. Banerjee)', role: 'Leader of "Young Bengal", Theologian, Linguist & President of Calcutta University Faculty', eraId: 'era-4', year: '1832 – 1885 AD', badgeType: 'native', badgeLabel: 'Priest & Theologian', icon: 'church', description: 'Prominent member of Young Bengal who converted under Duff. He became an Anglican priest and published *The Aryan Witness*, shaping indigenous Indian Christian philosophy.', image: 'images/krishna-mohan-banerjee.jpg' },
  { id: '36', name: 'Henry Bower', role: 'Chief Translator of the Bower Union Version Tamil Bible & Lexicographer', eraId: 'era-4', year: '1841 – 1885 AD', badgeType: 'foreign', badgeLabel: 'Bible Translator', icon: 'book', description: 'Chaired the committee that produced the standard "Bower Union Version" of the Tamil Bible (1871), praised for its grammatical balance and clarity.', image: 'images/henry-bower.jpg' },
  { id: '37', name: 'Robert Caldwell', role: 'Bishop in Tinnevelly & Father of Comparative Dravidian Linguistics', eraId: 'era-4', year: '1838 – 1891 AD', badgeType: 'foreign', badgeLabel: 'Bishop & Philologist', icon: 'church', description: 'Authored the monumental *Comparative Grammar of the Dravidian Languages* (1856), establishing the distinct identity of the Dravidian family. Served 50 years in Idayankudi.', image: 'images/robert-caldwell.jpg' },
  { id: '38', name: 'Rt. Rev. Edward Sargent', role: 'Bishop in Tinnevelly & Founder of Sarah Tucker College Institutions', eraId: 'era-4', year: '1838 – 1889 AD', badgeType: 'foreign', badgeLabel: 'Bishop in Tinnevelly', icon: 'church', description: 'Spent 50 years building schools in Palayamkottai, developing teacher training institutes and pioneering higher education for women through Sarah Tucker College.', image: 'images/edward-sargent.jpg' },
  { id: '39', name: 'Thomas Ragland', role: 'Pioneer of the North Tinnevelly Itinerant Tent Mission', eraId: 'era-4', year: '1846 – 1858 AD', badgeType: 'foreign', badgeLabel: 'Tent Evangelist', icon: 'church', description: 'Cambridge mathematician and fellow who lived in simple tents in rural North Tirunelveli, demonstrating non-institutional church planting models.', image: 'images/thomas-ragland.jpg' },
  { id: '40', name: 'G.U. Pope (George Uglow Pope)', role: 'Translator of Tirukkural & Thiruvasagam; Professor of Tamil at Oxford', eraId: 'era-4', year: '1839 – 1908 AD', badgeType: 'foreign', badgeLabel: 'Oxford Tamil Scholar', icon: 'book', description: 'Spent 40 years in Tamil Nadu before teaching at Oxford. Translated classical masterworks *Tirukkural*, *Thiruvasagam*, and *Naladiyar* into English.', image: 'images/gu-pope.jpg' },
  { id: '41', name: 'Rev. Lal Behari Dey', role: 'Pioneer Indian English Novelist, Folklorist & Presbyterian Minister', eraId: 'era-4', year: '1843 – 1892 AD', badgeType: 'native', badgeLabel: 'Minister & Novelist', icon: 'church', description: 'Authored *Govinda Samanta: or the History of a Bengal Raiyat* and *Folk-Tales of Bengal*, advocating for rural peasants and church autonomy.', image: 'images/lal-behari-dey.jpg' },
  { id: '42', name: 'Samuel Mateer', role: 'LMS Missionary in Travancore, Social Reformer & Renowned Ethnographer', eraId: 'era-4', year: '1859 – 1893 AD', badgeType: 'foreign', badgeLabel: 'LMS Ethnographer', icon: 'book', description: 'Wrote foundational anthropological works including *The Land of Charity* (1871) and *Native Life in Travancore* (1883), documenting the struggles of oppressed communities.', image: 'images/samuel-mateer.jpg' },
  { id: '43', name: 'Rev. N. Samuel of Tranquebar', role: 'Pastor, Professor of Theology & Renowned Tamil Christian Hymnist', eraId: 'era-4', year: '1850 – 1927 AD', badgeType: 'poet', badgeLabel: 'Pastor & Hymnist', icon: 'music', description: 'Taught at the Tranquebar Theological Seminary. Authored dozens of widely used Tamil Christian keerthanaigal adhering to strict classical Tamil poetic rules (Venba and Viruththam), compiled in *Sangeetha Keerthanaigal*.', highlights: ['Composed beloved hymns: "En Meetpar Uyirodirukkaiyile", "Thiruratha Paathiram Vaa".'], image: 'images/n-samuel-tranquebar.jpg' },
  { id: '44', name: 'G. S. Vedanayagam (Megnanapuram)', role: 'Lyricist, Catechist & Major Contributor to the Tamil Christian Hymnal', eraId: 'era-4', year: '1852 – 1910 AD', badgeType: 'poet', badgeLabel: 'Keerthanai Master', icon: 'music', description: 'Native poet from Tirunelveli whose deep devotional keerthanaigal are among the most sung songs across South Indian churches today. Known for heartfelt lyrical devotion set to traditional Carnatic melodies.', highlights: ['Composed cornerstone lyrics: "En Meetpar Ennai Kaankinraar", "Yesu Ennum Naamame En Idhayaththin Kaaname".'], image: 'images/gs-vedanayagam.jpg' },
  { id: '45', name: 'Arthur Margoschis', role: 'The "Father of Nazareth" & Industrial Education Pioneer', eraId: 'era-4', year: '1877 – 1908 AD', badgeType: 'foreign', badgeLabel: 'SPG Social Builder', icon: 'church', description: 'Built Nazareth (Tirunelveli) into a model industrial town with technical schools, hospitals, and St. John\'s High School / Margoschis College.', image: 'images/arthur-margoschis.jpg' },
  { id: '46', name: 'Rev. H.J. Schaffter', role: 'Principal & Builder of CMS College, Tirunelveli', eraId: 'era-4', year: '1877 – 1920 AD', badgeType: 'foreign', badgeLabel: 'CMS Educationist', icon: 'book', description: 'Developed CMS College High School in Tirunelveli, using academic rigor and sportsmanship to unify students across rigid social lines.', image: 'images/hj-schaffter.jpg' },

  // ERA 5
  { id: '47', name: 'Rao Sahib Abraham Pandithar (Thanjavur)', role: 'Father of Modern Tamil Musicology, Author of Karunamirtha Sagaram & Keerthanai Composer', eraId: 'era-5', year: '1859 – 1919 AD', badgeType: 'poet', badgeLabel: 'Musicologist & Hymnist', icon: 'music', description: 'A towering figure in Indian classical music who systematized ancient Tamil Isai theory in his magnum opus *Karunamirtha Sagaram*. He composed numerous Carnatic Christian keerthanaigal based on the 72 Melakarta ragas.', image: 'images/abraham-pandithar.jpg' },
  { id: '48', name: 'Narayan Vaman Tilak', role: 'Renowned Marathi Christian Poet, Hymnist & Author of Christayan', eraId: 'era-5', year: '1861 – 1919 AD', badgeType: 'poet', badgeLabel: 'Marathi Poet-Saint', icon: 'music', description: 'Brahmin scholar who converted to Christianity. Composed over 250 devotional Marathi bhajans and abhangas (forming over a third of the Marathi Protestant hymnal *Upasana Sangeet*) and began the epic *Christayan*.', image: 'images/narayan-vaman-tilak.jpg' },
  { id: '49', name: 'Rev. V. Santiago', role: 'Itinerant Revivalist, Pastor & Master Lyricist of Devotional Keerthanaigal', eraId: 'era-5', year: '1862 – 1940 AD', badgeType: 'poet', badgeLabel: 'Evangelist & Hymnist', icon: 'music', description: 'Served in the Madurai and Tirunelveli mission districts. Known for his soul-stirring devotional lyrics that became central to gospel conventions and prayer movements across Tamil Nadu.', highlights: ['Composed enduring keerthanaigal: "Aathumame En Muzhu Ullame", "Kartharaiye Naan Ekkalaththilum".'], image: 'images/v-santiago.jpg' },
  { id: '50', name: 'Thomas Walker ("Walker of Tinnevelly")', role: 'Keswick Revivalist, Tamil Scholar & Mentor of the 1905 Revivals', eraId: 'era-5', year: '1885 – 1912 AD', badgeType: 'foreign', badgeLabel: 'CMS Revivalist', icon: 'church', description: 'Stationed in Dohnavur. Renowned convention speaker and mentor to Amy Carmichael and Bishop Azariah, spearheading major spiritual revivals across South India.', image: 'images/thomas-walker.jpg' },
  { id: '51', name: 'Pandita Ramabai Sarasvati', role: 'Founder of Mukti Mission (Pune) & Hebrew/Greek-to-Marathi Bible Translator', eraId: 'era-5', year: '1887 – 1922 AD', badgeType: 'native', badgeLabel: 'Scholar & Reformer', icon: 'book', description: 'Foremost woman scholar who founded Mukti Mission (1897) to shelter young widows and orphans. Translated the complete Bible directly from original Hebrew and Greek into Marathi.', image: 'images/pandita-ramabai.jpg' },
  { id: '52', name: 'Amy Carmichael (Ammaiah)', role: 'Founder of the Dohnavur Fellowship & Rescuer of Temple Children', eraId: 'era-5', year: '1895 – 1951 AD', badgeType: 'foreign', badgeLabel: 'Dohnavur Fellowship', icon: 'church', description: 'Lived in Tirunelveli for 56 continuous years without furlough. Founded the Dohnavur Fellowship, rescuing vulnerable infants and young girls dedicated to temple servitude.', image: 'images/amy-carmichael.jpg' },
  { id: '53', name: 'Dr. Ida S. Scudder', role: 'Founder of Christian Medical College (CMC) Vellore & Healthcare Crusader', eraId: 'era-5', year: '1900 – 1960 AD', badgeType: 'foreign', badgeLabel: 'CMC Vellore Founder', icon: 'medical', description: 'Granddaughter of John Scudder Sr. Founded CMC Vellore, pioneering modern medical education for Indian women and roadside rural healthcare clinics.', image: 'images/ida-scudder.jpg' },
  { id: '54', name: 'Sadhu Sundar Singh', role: 'The "Apostle with the Bleeding Feet" (Himalayas, Tibet & Global Ministry)', eraId: 'era-5', year: '1905 – 1929 AD', badgeType: 'native', badgeLabel: 'Christian Sadhu', icon: 'church', description: 'Converted from Sikhism in Punjab and adopted the saffron robe of a wandering Christian Sadhu, traversing the Himalayas and Tibet to present Christ in indigenous Asian forms.', image: 'images/sadhu-sundar-singh.jpg' },
  { id: '55', name: 'Rt. Rev. Vedanayagam Samuel Azariah', role: 'First Indian Anglican Bishop (Dornakal) & Founder of IMS & NMS', eraId: 'era-5', year: '1903 – 1945 AD', badgeType: 'native', badgeLabel: 'Indigenous Bishop', icon: 'church', description: 'Co-founded the Indian Missionary Society (IMS, 1903) and the National Missionary Society (NMS, 1905). Consecrated as India\'s first indigenous Anglican Bishop in 1912, leading mass movements for Dalit empowerment.', image: 'images/vs-azariah.jpg' }
];
